# Generated by Django 5.2.10 on 2026-01-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_completed_at_booking_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
