"""
Mock data for development and testing
"""
from datetime import datetime

MOCK_PROVIDERS = [
    {
        'id': '1',
        'name': 'Adv. Priya Sharma',
        'email': 'priya.sharma@example.com',
        'phone': '+91 98765 43210',
        'provider_type': 'advocate',
        'bar_registration_number': 'BCI/2015/12345',
        'years_of_experience': 8,
        'specializations': ['family', 'property'],
        'languages': ['English', 'Hindi', 'Marathi'],
        'city': 'Mumbai',
        'state': 'Maharashtra',
        'rating': 4.8,
        'review_count': 156,
        'completed_cases': 234,
        'response_time': '2 hours',
        'availability_status': 'available',
        'hourly_rate': 2500,
        'bio': 'Experienced family law advocate with expertise in divorce, custody, and property disputes. Committed to providing compassionate and effective legal solutions.',
        'incentive_points': 1250,
        'badges': [
            {'name': 'Top Rated', 'description': 'Maintained 4.5+ rating for 6 months', 'icon': '⭐'},
            {'name': 'Quick Responder', 'description': 'Average response time under 3 hours', 'icon': '⚡'},
        ],
        'verification_status': 'verified',
        'profile_image': '/static/images/professional-indian-woman-lawyer.jpg',
    },
    {
        'id': '2',
        'name': 'Adv. Rajesh Kumar',
        'email': 'rajesh.kumar@example.com',
        'phone': '+91 98765 43211',
        'provider_type': 'advocate',
        'bar_registration_number': 'BCI/2012/67890',
        'years_of_experience': 12,
        'specializations': ['criminal', 'civil'],
        'languages': ['English', 'Hindi', 'Tamil'],
        'city': 'Chennai',
        'state': 'Tamil Nadu',
        'rating': 4.9,
        'review_count': 203,
        'completed_cases': 345,
        'response_time': '1 hour',
        'availability_status': 'available',
        'hourly_rate': 3000,
        'bio': 'Senior advocate specializing in criminal defense and civil litigation. Known for thorough case preparation and courtroom excellence.',
        'incentive_points': 2100,
        'badges': [
            {'name': 'Top Rated', 'description': 'Maintained 4.5+ rating for 6 months', 'icon': '⭐'},
            {'name': 'Pro Bono Champion', 'description': 'Completed 10+ pro bono cases', 'icon': '🏆'},
        ],
        'verification_status': 'verified',
        'profile_image': '/static/images/professional-indian-man-lawyer.jpg',
    },
    {
        'id': '3',
        'name': 'Mediation Expert Anil Desai',
        'email': 'anil.desai@example.com',
        'phone': '+91 98765 43212',
        'provider_type': 'mediator',
        'years_of_experience': 15,
        'specializations': ['family', 'property', 'civil'],
        'languages': ['English', 'Hindi', 'Gujarati'],
        'city': 'Ahmedabad',
        'state': 'Gujarat',
        'rating': 4.7,
        'review_count': 89,
        'completed_cases': 167,
        'response_time': '3 hours',
        'availability_status': 'available',
        'hourly_rate': 2000,
        'bio': 'Certified mediator with extensive experience in resolving family and property disputes through alternative dispute resolution.',
        'incentive_points': 890,
        'badges': [
            {'name': 'Peacemaker', 'description': 'Successfully mediated 50+ disputes', 'icon': '🤝'},
        ],
        'verification_status': 'verified',
        'profile_image': '/static/images/professional-indian-mediator.jpg',
    },
    {
        'id': '4',
        'name': 'Adv. Sneha Reddy',
        'email': 'sneha.reddy@example.com',
        'phone': '+91 98765 43213',
        'provider_type': 'advocate',
        'bar_registration_number': 'BCI/2018/11111',
        'years_of_experience': 6,
        'specializations': ['corporate', 'tax'],
        'languages': ['English', 'Hindi', 'Telugu'],
        'city': 'Hyderabad',
        'state': 'Telangana',
        'rating': 4.6,
        'review_count': 78,
        'completed_cases': 120,
        'response_time': '4 hours',
        'availability_status': 'available',
        'hourly_rate': 2800,
        'bio': 'Corporate lawyer specializing in business law, tax matters, and corporate compliance. Helping businesses navigate legal complexities.',
        'incentive_points': 650,
        'badges': [
            {'name': 'Rising Star', 'description': 'Fastest growing profile this quarter', 'icon': '🌟'},
        ],
        'verification_status': 'verified',
        'profile_image': '/static/images/professional-indian-woman-lawyer-2.jpg',
    },
    {
        'id': '5',
        'name': 'Notary Vikram Singh',
        'email': 'vikram.singh@example.com',
        'phone': '+91 98765 43214',
        'provider_type': 'notary',
        'years_of_experience': 20,
        'specializations': ['property', 'civil'],
        'languages': ['English', 'Hindi', 'Punjabi'],
        'city': 'Delhi',
        'state': 'Delhi',
        'rating': 4.5,
        'review_count': 312,
        'completed_cases': 1500,
        'response_time': '1 hour',
        'availability_status': 'available',
        'hourly_rate': 1500,
        'bio': 'Government-appointed notary public with two decades of experience in document authentication and legal attestation.',
        'incentive_points': 1800,
        'badges': [
            {'name': 'Veteran', 'description': '10+ years of service', 'icon': '🎖️'},
            {'name': 'Volume Champion', 'description': 'Completed 1000+ cases', 'icon': '📊'},
        ],
        'verification_status': 'verified',
        'profile_image': '/static/images/professional-indian-notary.jpg',
    },
]

MOCK_SERVICE_LISTINGS = [
    {
        'id': 's1',
        'provider_id': '1',
        'title': 'Divorce Consultation & Filing',
        'description': 'Comprehensive divorce consultation including documentation, filing, and court representation for mutual or contested divorce cases.',
        'category': 'family',
        'price_min': 15000,
        'price_max': 50000,
        'duration': '3-6 months',
        'delivery_time': 'As per court schedule',
        'features': [
            'Initial consultation',
            'Document preparation',
            'Court filing',
            'Court representation',
            'Regular updates',
        ],
    },
    {
        'id': 's2',
        'provider_id': '1',
        'title': 'Property Documentation Review',
        'description': 'Thorough review of property documents including title deeds, sale agreements, and verification of legal ownership.',
        'category': 'property',
        'price_min': 5000,
        'price_max': 15000,
        'duration': '1-2 weeks',
        'delivery_time': '7-14 days',
        'features': ['Document verification', 'Title search', 'Legal opinion', 'Risk assessment', 'Detailed report'],
    },
    {
        'id': 's3',
        'provider_id': '2',
        'title': 'Criminal Defense Representation',
        'description': 'Complete criminal defense services including bail applications, trial representation, and appeal proceedings.',
        'category': 'criminal',
        'price_min': 25000,
        'price_max': 100000,
        'duration': 'Case dependent',
        'delivery_time': 'Immediate response',
        'features': [
            'Emergency consultation',
            'Bail application',
            'Trial preparation',
            'Court representation',
            'Appeal support',
        ],
    },
]

TRIAGE_QUESTIONS = [
    {
        'id': 'q1',
        'question': 'What type of legal issue are you facing?',
        'type': 'single',
        'category': 'other',
        'options': [
            'Family matters (divorce, custody, maintenance)',
            'Property disputes (ownership, rental, documentation)',
            'Criminal cases (FIR, bail, defense)',
            'Civil disputes (contracts, money recovery)',
            'Corporate/Business matters',
            'Labor/Employment issues',
            'Tax-related matters',
            'Consumer complaints',
            'Other legal issues',
        ],
    },
    {
        'id': 'q2',
        'question': 'How urgent is your legal matter?',
        'type': 'single',
        'category': 'other',
        'options': [
            'Emergency (need help today)',
            'Urgent (within a week)',
            'Normal (within a month)',
            'Not urgent (planning ahead)',
        ],
    },
    {
        'id': 'q3',
        'question': 'What is your preferred language for communication?',
        'type': 'single',
        'category': 'other',
        'options': [
            'English',
            'Hindi',
            'Regional language',
        ],
    },
]

LEGAL_CATEGORIES = [
    {'id': 'family', 'name': 'Family Law', 'icon': '👨‍👩‍👧‍👦', 'description': 'Divorce, custody, maintenance, domestic issues'},
    {'id': 'property', 'name': 'Property Law', 'icon': '🏠', 'description': 'Real estate, land disputes, documentation'},
    {'id': 'criminal', 'name': 'Criminal Law', 'icon': '⚖️', 'description': 'Criminal defense, bail, FIR matters'},
    {'id': 'civil', 'name': 'Civil Law', 'icon': '📋', 'description': 'Contracts, disputes, money recovery'},
    {'id': 'corporate', 'name': 'Corporate Law', 'icon': '🏢', 'description': 'Business law, compliance, contracts'},
    {'id': 'labor', 'name': 'Labor Law', 'icon': '👷', 'description': 'Employment issues, workplace disputes'},
    {'id': 'tax', 'name': 'Tax Law', 'icon': '💰', 'description': 'Tax planning, disputes, compliance'},
    {'id': 'consumer', 'name': 'Consumer Law', 'icon': '🛒', 'description': 'Consumer rights, complaints, refunds'},
]
